### ISSUE TITLE
Problem with sending email

### ISSUE THREAD

**Issue by eduardodiasc** [mohamedsamara/mern-ecommerce#106]
Hello.
First of all, congratulations for the excellent work.

I found a problem sending email.
When I register, I'm not sending an email because it gives the error below.

If I just pass the firstName, it works.

1) template.js
exports.signupEmail = name => {
  const message = {
    subject: 'Account Registration',
    text: `Hi ${name.firstName} ${name.lastName}! Thank you for creating an account with us!.`
  };

### Error

TypeError: Cannot read properties of undefined (reading 'firstName')
    at Object.exports.signupEmail (/Volumes/Dudu/Projetos/mern-ecommerce/server/config/template.js:54:22)
    at prepareTemplate (/Volumes/Dudu/Projetos/mern-ecommerce/server/services/mailgun.js:54:26)
    at Object.exports.sendEmail (/Volumes/Dudu/Projetos/mern-ecommerce/server/services/mailgun.js:25:21)
    at /Volumes/Dudu/Projetos/mern-ecommerce/server/routes/api/auth.js:128:19
    at runMicrotasks (<anonymous>)

**Comment by mohamedsamara** [comment]
Thank you @eduardodiasc! Will double check that.
