### ISSUE TITLE
MongoDB `facebookId_1` duplicate `null` key

### ISSUE THREAD

**Issue by SnekNOTSnake** [mohamedsamara/mern-ecommerce#22]
Mongod version: 4.4.2

```
MongoError: E11000 duplicate key error collection: mern-ecommerce-test.users index: facebookId_1 dup key: { facebookId: null }
    at Function.create (/home/sneknotsnake/reactjs/mern-ecommerce/node_modules/mongodb/lib/core/error.js:57:12)
    at toError (/home/sneknotsnake/reactjs/mern-ecommerce/node_modules/mongodb/lib/utils.js:123:22)
    at /home/sneknotsnake/reactjs/mern-ecommerce/node_modules/mongodb/lib/operations/common_functions.js:265:39
    at handler (/home/sneknotsnake/reactjs/mern-ecommerce/node_modules/mongodb/lib/core/sdam/topology.js:942:24)
    at /home/sneknotsnake/reactjs/mern-ecommerce/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
    at handleOperationResult (/home/sneknotsnake/reactjs/mern-ecommerce/node_modules/mongodb/lib/core/sdam/server.js:558:5)
    at MessageStream.messageHandler (/home/sneknotsnake/reactjs/mern-ecommerce/node_modules/mongodb/lib/cmap/connection.js:277:5)
    at MessageStream.emit (events.js:315:20)
    at MessageStream.EventEmitter.emit (domain.js:467:12)
    at processIncomingData (/home/sneknotsnake/reactjs/mern-ecommerce/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/sneknotsnake/reactjs/mern-ecommerce/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  driver: true,
  index: 0,
  code: 11000,
  keyPattern: { facebookId: 1 },
  keyValue: { facebookId: null }
}
```

Steps to reproduce (at least in my machine):

- Create two accounts that don't use facebook

I was able to solve this problem using this [stackoverflow answer](https://stackoverflow.com/a/24430345/10930293), but IDK why  is this only happening to me.

**Comment by karthikeyana** [comment]
I had the same problem while I social media signup. when the user joins using email first-time work without any issue. when another user signup using email there is an issue due to a null value assigned to the social media id. the reason is only one user should be allowed to insert a null value according to unique true constrain.

**Error Schema:**

    facebookId: {
        type: String,
        index:true
      },

**Solution Schema:** 
1) Drop the existing index created against facebookId
   [![db.users.dropIndex(facebookid_)][1]][1]

2)when we use `sparse: true` property it allows us to store multiple null values 

      facebookId: {
        type: String,
        index:true,
        unique:true,
        sparse:true
      },


  [1]: https://i.stack.imgur.com/i4El5.png

**Comment by TrustFirst12** [comment]
I installed the project and run the application for the project.
And I got the following error.

![image](https://user-images.githubusercontent.com/80338585/110815167-1150f180-823f-11eb-9096-7e6fbcedb72e.png)

Could you explain why this happens and how to fix it?
Thank you.

**Comment by mohamedsamara** [comment]
@TrustFirst12 Mailchimp keys are missing, these keys are secrets and are not shared between projects. You need to obtain them from your Mailchimp account and put them in an .env file in the project. Here is an example of the [env](https://github.com/mohamedsamara/mern-ecommerce/blob/master/.env.example) file.

**Comment by Walf-dev** [comment]
Thanks guys for all. You made a great job!

However, I'm facing a problem.
Adding an image when creating a product results in the following error: 
"Please Try Again!
Your request could not be processed.
Please try again."

Is the problem due to the size of the database or something else?

Please how can I solve this?

**Comment by mohamedsamara** [comment]
@Walf-dev This is a generic error that is passed to the frontend app. If you want to see the error you can log it on this [line](https://github.com/mohamedsamara/mern-ecommerce/blob/master/server/routes/api/product.js#L101). Adding an image will use AWS S3 Bucket so make sure you add the [keys](https://github.com/mohamedsamara/mern-ecommerce/blob/master/.env.example#L18) that are associated with your S3 Bucket on AWS account.
