### ISSUE TITLE
Initialization Error

### ISSUE THREAD

**Issue by juliansalazar** [mohamedsamara/mern-ecommerce#241]
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): **\*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
Missing mailgun keys
Failed to load ./.env.
C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\server\node_modules\passport-jwt\lib\strategy.js:45
        throw new TypeError('JwtStrategy requires a secret or key');
        ^

TypeError: JwtStrategy requires a secret or key
    at new JwtStrategy (C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\server\node_modules\passport-jwt\lib\strategy.js:45:15)
    at Object.<anonymous> (C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\server\config\passport.js:21:3)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\server\index.js:26:1)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.12.2
[nodemon] app crashed - waiting for file changes before starting...
i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client
i ｢wds｣: 404s will fallback to /index.html
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:80:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
node:internal/crypto/hash:80
  this[kHandle] = new _Hash(algorithm, xofLen, algorithmId, getHashCache());
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:80:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Users\User\Desktop\ecommerce-autocarest\mern-ecommerce\client\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by SaquibShahid** [comment]
It was due to some secret key they have kept in their .env file , which was not present when you cloned this repo.

**Comment by mohamedsamara** [comment]
@juliansalazar there are two errors in the log you posted:

1. "JwtStrategy requires a secret or key". This a missing JWT Secret Key. [See guide on ENV here](https://github.com/mohamedsamara/mern-ecommerce/blob/master/server/.env.example)
2. "Error: error:0308010C:digital envelope routines::unsupported". This is an error due to webpack 4 support  for node >= 18. It is fixed in a044fa0d4eb336ae1ae4f63dfc99c2e1a5b9282d
